CCTH_Administrador_Pedidos/CCTH_Administrador_Pedidos/Models/Log.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CCTH_Administrador_Pedidos.Models
{
    public class Log
    {
        public int Id { get; set; }
        public DateTime DeliveryDate { get; set; }
        public int CedisId { get; set; }
        public int RouteId { get; set; }
        public int Trip { get; set; }
        public Process Process { get; set; }
        public Enums.ProcessStatus ProcessStatus { get; set; }
        public List<LogDetail> LogDetail { get; set; }
    }
}

CCTH_Administrador_Pedidos/CCTH_Administrador_Pedidos/Controllers/LogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CCTH_Administrador_Pedidos.Controllers.DataAcces;
using CCTH_Administrador_Pedidos.Models;
using CCTH_Administrador_Pedidos.Models.Dtos;
using CCTH_Administrador_Pedidos.Models.ViewModels;

namespace CCTH_Administrador_Pedidos.Controllers
{
    public class LogsController : Controller
    {
        private readonly APIIntermediaLogsController _logsRepository = new APIIntermediaLogsController();

        public ActionResult Index()
        {
            var cedisId = Convert.ToInt32(Session["Cedi"]);
            ViewBag.CedisId = cedisId;
            ViewBag.Routes = new APIIntermediaDestinoController().Get().Where(route => route.Cedis == cedisId).ToList();
            ViewBag.ShowView = "Reportes";
            return View();
        }

        public JsonResult GetLogsForDataTable(int draw, DateTime? deliveryDate = null, int? cedisId = null, int? routeId = null, int? trip = null, int? processStatus = null, int? start = null, int? length = null)
        {
            
            var logs = _logsRepository.FindLogsForDataTable(deliveryDate, cedisId, routeId, trip, processStatus, start, length);
            var dataTableLogs = new List<DataTableLog>();
            logs.data.ForEach(log => dataTableLogs.Add(new DataTableLog
            {
                Id = log.Id,
                DeliveryDate = log.DeliveryDate.ToString("dd/MM/yyyy"),
                CedisId = log.CedisId,
                RouteId = log.RouteId,
                Trip = log.Trip,
                ProcessDescription = log.Process.Description,
                ProcessStatus = Enum.GetName(typeof(Enums.ProcessStatus), log.ProcessStatus)
            }));
            return Json(new { draw = draw, recordsTotal = logs.totalRecords, recordsFiltered = logs.filteredRecords, data = dataTableLogs }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int id)
        {
            var log = _logsRepository.Find(id);
            ViewBag.ShowView = "Reportes";
            return View(log);
        }
       
    }
}

CCTH_Administrador_Pedidos/CCTH_Administrador_Pedidos/Views/Logs/Details.cshtml
@model CCTH_Administrador_Pedidos.Models.Log

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_PanelAdminCCTH.cshtml";
}

<h2>Detalle de Bitácora</h2>

<div class="row">

    <div class="col s12 m2 label">
        <span class="bold">CEDIS</span>
    </div>
    <div class="col s12 m6">
        @Html.EditorFor(model => model.CedisId, new { htmlAttributes = new { @class = "form-control inputControl notEditable" } })
    </div>
</div>
<div class="row">

    <div class="col s12 m2 label">
        <span class="bold">RUTA</span>
    </div>
    <div class="col s12 m6">
        @Html.EditorFor(model => model.RouteId, new { htmlAttributes = new { @class = "form-control inputControl notEditable" } })
    </div>
</div>
<div class="row">

    <div class="col s12 m2 label">
        <span class="bold">VIAJE</span>
    </div>
    <div class="col s12 m6">
        @Html.EditorFor(model => model.Trip, new { htmlAttributes = new { @class = "form-control inputControl notEditable" } })
    </div>
</div>
<div class="row">

    <div class="col s12 m2 label">
        <span class="bold">FECHA DE ENTREGA</span>
    </div>
    <div class="col s12 m6">
        @{var deliveryDateLbl = Model.DeliveryDate.ToString("dd/MM/yyyy");}
        <input type="text" class="form-control inputControl notEditable" value="@deliveryDateLbl" />
    </div>
</div>

<div class="row">

    <div class="col s12 m2 label">
        <span class="bold">PROCESO</span>
    </div>
    <div class="col s12 m6">
        @Html.EditorFor(model => model.Process.Description, new { htmlAttributes = new { @class = "form-control inputControl notEditable" } })
    </div>
</div>
<div class="row">

    <div class="col s12 m2 label">
        <span class="bold">ESTATUS</span>
    </div>
    <div class="col s12 m6">
        @{ var estadoProcesoLbl = Enum.GetName(typeof(CCTH_Administrador_Pedidos.Enums.ProcessStatus), Model.ProcessStatus);}
        @estadoProcesoLbl
    </div>
</div>
<table id="logsTable">
    <thead>
        <th>Id</th>
        <th>Descripcion</th>
        <th>Estado</th>
    </thead>
    <tbody>

        @foreach (var detail in Model.LogDetail)
        {
            var estadoLbl = detail.Success == true ? "CORRECTO" : "FALLIDO";
            <tr>
                <td>@detail.Id</td>
                <td>@detail.ErrorDescription</td>
                <td>@estadoLbl</td>
            </tr>
        }
    </tbody>
</table>
<script src="~/Scripts/jquery-2.1.1.min.js"></script>
<script>
    $(document).ready(function () {
        $('.notEditable').prop('disabled', true);
    });
</script>

CCTH_Administrador_Pedidos/CCTH_Administrador_Pedidos/Views/Logs/Index.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_PanelAdminCCTH.cshtml";
}

<h2>Bitácora</h2>
<div id="hiddenValues">
    <input type="hidden" id="cedisId" value="@ViewBag.CedisId"/>
</div>
<div class="row" id="filtros">
    <div class="col s12 m2">
        <input id="deliveryDate" type="date" class="validate">
        <label for="deliveryDate">Fecha</label>
    </div>
    <div class="col s12 m2">
        <select name="routeId" id="route-select" class="browser-default">
            <option value="">TODAS</option>
            @foreach (var route in ViewBag.Routes)
            {
                <option value="@route.RouteCodeOpecd">@route.Nombre</option>
            }
        </select>
        <label>Ruta</label>
    </div>
    <div class="col s12 m2">
        <select name="statusId" id="status-select" class="browser-default">
            <option value="">TODOS</option>
            <option value="1">PROCESO</option>
            <option value="2">CORRECTO</option>
            <option value="3">FALLO</option>
        </select>
        <label>Estatus</label>
    </div>
    <div class="col s12 m2">
        <button type="button" onclick="reloadTable()" class="btn btn-default colorthme">Buscar</button>
    </div>
</div>
<div class="row">
    <div class="col s12">
        <table id="logsTable" class="striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>CEDIS</th>
                    <th>RUTA</th>
                    <th>VIAJE</th>
                    <th>FECHA ENTREGA</th>
                    <th>PROCESO</th>
                    <th>STATUS</th>
                    <th>DETALLES</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" type="text/css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script>

    let table;

    $(document).ready(function () {
        table = loadTable(createUriForSearching());
    });

    function loadTable(uriForSearching, callback) {
        carga();
        return $('#logsTable').DataTable({
            "initComplete": function (settings, json) {
                ocultarCarga();
            },
            "paging": true,
            "pageLength": 10,
            "searching": false,
            "ajax": {
                "url": uriForSearching,
                "type": "GET",
                "datatype": "json"
            },
            "columns": [
                { "data": "Id" },
                { "data": "CedisId" },
                { "data": "RouteId" },
                { "data": "Trip" },
                { "data": "DeliveryDate" },
                { "data": "ProcessDescription" },
                { "data": "ProcessStatus" },
                {
                    "render": function (data, type, row, meta) {
                        return "<a href='Logs/Details/" + row.Id + "'> DETALLES </a>";
                    }
                }
            ],
            "serverSide": true
        });
    }

    function createUriForSearching() {
        var cedisId = $("#cedisId").val();
        var routeId = $("#route-select").val();
        var deliveryDate = $("#deliveryDate").val();
        var status = $('#status-select').val();

        var uriForSearching = "@Url.Action("GetLogsForDataTable", "Logs")";
        var filtersChain = "?&cedisId=" + cedisId;
        if (isSet(routeId))
            filtersChain += "&routeId=" + routeId;
        if (isSet(deliveryDate))
            filtersChain += "&deliveryDate=" + deliveryDate;
        if (isSet(status))
            filtersChain += "&processStatus=" + status;

        return uriForSearching + filtersChain;
    }

    function isSet(str) {
        if (typeof (str) === 'undefined' || str === null || str === "")
            return false;
        return true;
    }

    function reloadTable() {
        carga();
        table.destroy();
        table = loadTable(createUriForSearching());
    }

    function today() {
        let date = new Date;
        let stringDate = `${date.getFullYear()}/${date.getMonth() + 1}/${date.getDay()}`;
        return stringDate;
    }

    
</script>

