CCTH_Administrador_Pedidos/CCTH_Administrador_Pedidos/Controllers/ReportsController.cs
using CCTH_Administrador_Pedidos.Controllers.Utils;
using CCTH_Administrador_Pedidos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CCTH_Administrador_Pedidos.Controllers
{
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {
            if (new SessionAdminPedidos().validateSession((LoginResponse)Session["UserID"])) 
            {
                ViewBag.ShowView = "Reportes";
                ViewBag.Option = "Index";
                return View();
            }
            return RedirectToAction("Index", "Home");
        }
        public JsonResult GetSales() {
            if (new SessionAdminPedidos().validateSession((LoginResponse)Session["UserID"])) 
            {
                List<EncVentas> sales = new List<EncVentas>();
                return Json(new { data = sales }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Error = "Inicia sesion." }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SalesReportDetails() {
            if (new SessionAdminPedidos().validateSession((LoginResponse)Session["UserID"])) 
            {
                ViewBag.ShowView = "Reportes";
                ViewBag.Option = "Index";
                return View();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

CCTH_Administrador_Pedidos/CCTH_Administrador_Pedidos/Views/Reports/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PanelAdminCCTH.cshtml";
}

<div class="row">
    <div class="col s12">
        <div class="row">
            <h4>Ventas</h4>
            <table id="reportsTable">
                <thead>
                    <tr>
                        <th style="width:10%;text-align:center;">CODOPE</th>
                        <th style="width:15%;text-align:center;">CUC</th>
                        <th style="width:15%;text-align:center;">WBC ID</th>
                        <th style="width:15%;text-align:center;">TIPO</th>
                        <th style="width:15%;text-align:center;">FACTURADO</th>
                        <th style="width:15%;text-align:center;">RAZON DEVOLUCION</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<link rel="stylesheet" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" type="text/css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script>

    let table;
    let uriForGettingReports = "@Url.Action("GetSales","Reports")";

    $(document).ready(function(){
        table = loadTable(uriForGettingReports);
    });

        function loadTable(uriForSearching) {
            return $('#reportsTable').DataTable({
                "paging": true,
                "pageLength": 20,
                "ordering": true,
                "info": false,
                "searching": false,
                "ajax": {
                    "url": uriForSearching,
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    {"data": "Id"},
                    { "data": "Codope" },
                    { "data": "CUC" },
                    { "data": "WBCSaleId" },
                    { "data": "Facturado" },
                    { "data": "RazonDev" }
                ]
            });
        }
</script>

CCTH_Administrador_Pedidos/CCTH_Administrador_Pedidos/Views/Reports/SalesReportDetails.cshtml

@{
    ViewBag.Title = "SalesReportDetails";
    Layout = "~/Views/Shared/_PanelAdminCCTH.cshtml";
}

<h2>SalesReportDetails</h2>
